package com.alef.souqleader.ui.constants

object Constants {
     val BASE_URL = "https://company1.realstatecrm-development.dev.alefsoftware.com/"
    const val ACCESS_TOKEN = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2NvbXBhbnkxLnJlYWxzdGF0ZWNybS1kZXZlbG9wbWVudC5kZXYuYWxlZnNvZnR3YXJlLmNvbS9hcGkvbG9naW4iLCJpYXQiOjE3MTg4NzU4NzksImV4cCI6MTcxOTQ4MDY3OSwibmJmIjoxNzE4ODc1ODc5LCJqdGkiOiJTWUpyekNINzhyQ2w3d2QxIiwic3ViIjoiNSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.9KF464SG-ZI8C0KQbKZ1nWIHGWvUvox8twOyTKqLvhE"
}