default_platform(:android)

platform :android do

  desc "Build AAB and upload to Google Play"
  lane :upload_to_playstore do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'internal',
      json_key: "fastlane/service-account.json",
      package_name: "com.alef.souqleader",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end